### ISSUE TITLE
Page with info about Harvard Dataverse collaboration

### ISSUE THREAD

**Issue by mercecrosas** [IQSS/dataverse.org#52] opened 2015-04-08 19:47 UTC
@posixeleni we need a page in dataverse.org to explain (very briefly) the Harvard Library and IT collaboration for Harvard Dataverse. We'll link to this page from the Harvard Dataverse banner.

**Comment by posixeleni** [comment] 2015-04-09 01:39
@mcrosas when would you like this done by?

**Comment by mcrosas** [comment] 2015-04-09 19:26
Text is being reviewed. I'll add it to the About page when confirmed.

**Comment by mcrosas** [comment] 2015-04-17 23:40
@posixeleni when you have a chance, here is the text to add at dataverse.org:

Since 2012, the Institute for Quantitative Social Science has collaborated with Harvard Library and Harvard University Information Technology (HUIT) to make the Harvard Dataverse <http://dataverse.harvard.edu> openly available to researchers and data collectors worldwide from all disciplines to deposit data. In this collaboration IQSS leads the development of the open source Dataverse software; and in conjunction with the Open Data Assistance Program at Harvard <http://projects.iq.harvard.edu/odap/home> (a collaboration with Harvard Library, the Office for Scholarly Communication and IQSS) provides user support for the Harvard Dataverse. The Library Technology Services at HUIT provides hosting and backups support of the Harvard Dataverse.

**Comment by posixeleni** [comment] 2015-04-19 22:40
@mcrosas updated the About.html page in dataverse.org. Need confirmation from @mheppler and @pdurbin as to how this page http://dataverse.org/about/ would be updated since its not Sphinx and it does not appear to automatically updated when I put in the changes.

**Comment by pdurbin** [comment] 2015-04-20 00:20
@posixeleni to me it looks like it was updated. For non-Sphinx (Django) info I'd check with @raprasad

**Comment by posixeleni** [comment] 2015-04-20 12:49
@pdurbin @raprasad @mheppler looks like the page automatically updated without any need for manual intereference so I will close this ticket.

**Comment by sbarbosadataverse** [comment] 2016-07-27 17:38
@dliburd @mcrosas Is this relevant to the collaborations page we discussed Dwayne creating in dataverse.org? I want to add him to this ticket is so. I removed Eleni as the assignee.

**Comment by mcrosas** [comment] 2016-07-27 21:39
Sonia, this issue can be closed.

We'll need to create a new collaboration page in dataverse.org, once
@dliburd has worked on the content for that page (in a google doc, for
example)

On Wed, Jul 27, 2016 at 1:38 PM, sbarbosadataverse <notifications@github.com

**Comment by sbarbosadataverse** [comment] 2016-07-28 01:08
Ok! Thanks!

**Comment by pdurbin** [comment] 2019-04-08 00:57
> Sonia, this issue can be closed.

Closing.

**Closed by pdurbin** 2019-04-08 00:57 UTC
